{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-provider-huawei.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUAWEICLOUD_SDK_AK: {{ .Values.credentials.accessKey | quote }}
  HUAWEICLOUD_SDK_SK: {{ .Values.credentials.secretKey | quote }}
  HUAWEICLOUD_SDK_REGION_ID: {{ .Values.credentials.region | quote }}
  {{- if .Values.credentials.projectId }}
  HUAWEICLOUD_SDK_PROJECT_ID: {{ .Values.credentials.projectId | quote }}
  {{- end }}
  HUAWEICLOUD_SDK_CCE_CLUSTER_ID: {{ coalesce .Values.clusterInfo.clusterID .Values.clusterInfo.ClusterID "" | quote }}
  {{- if .Values.credentials.bssEndpoint }}
  HUAWEICLOUD_BSS_ENDPOINT: {{ .Values.credentials.bssEndpoint | quote }}
  {{- end }}
{{- end }}
