{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-provider-huawei.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUAWEICLOUD_AK: {{ .Values.credentials.accessKey | quote }}
  HUAWEICLOUD_SK: {{ .Values.credentials.secretKey | quote }}
  HUAWEICLOUD_REGION: {{ .Values.credentials.region | quote }}
  HUAWEICLOUD_CCE_CLUSTER_ID: {{ coalesce .Values.credentials.clusterID .Values.credentials.ClusterID "" | quote }}
{{- end }}
