{{- if .Values.credentials.create }}
{{- $regionKey := upper (replace "-" "_" .Values.credentials.region) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-provider-huawei.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUAWEICLOUD_SDK_AK: {{ .Values.credentials.accessKey | quote }}
  HUAWEICLOUD_SDK_SK: {{ .Values.credentials.secretKey | quote }}
  HUAWEICLOUD_SDK_REGION_ID: {{ .Values.credentials.region | quote }}
  HUAWEICLOUD_SDK_CCE_CLUSTER_ID: {{ coalesce .Values.clusterInfo.clusterID .Values.clusterInfo.ClusterID "" | quote }}
  HUAWEICLOUD_SDK_PROJECT_ID: {{ .Values.sdk.projectID | quote }}
  HUAWEICLOUD_SDK_DOMAIN_ID: {{ .Values.sdk.domainID | quote }}
  HUAWEICLOUD_SDK_IAM_ENDPOINT: {{ .Values.sdk.iamEndpoint | quote }}
  HUAWEICLOUD_SDK_IGNORE_SSL_VERIFICATION: {{ .Values.sdk.ignoreSSLVerification | quote }}
  {{- if and .Values.credentials.region .Values.sdk.endpoints.ecs }}
  {{ printf "HUAWEICLOUD_SDK_REGION_ECS_%s" $regionKey }}: {{ .Values.sdk.endpoints.ecs | quote }}
  {{- end }}
  {{- if and .Values.credentials.region .Values.sdk.endpoints.vpc }}
  {{ printf "HUAWEICLOUD_SDK_REGION_VPC_%s" $regionKey }}: {{ .Values.sdk.endpoints.vpc | quote }}
  {{- end }}
  {{- if and .Values.credentials.region .Values.sdk.endpoints.cce }}
  {{ printf "HUAWEICLOUD_SDK_REGION_CCE_%s" $regionKey }}: {{ .Values.sdk.endpoints.cce | quote }}
  {{- end }}
  {{- if and .Values.credentials.region .Values.sdk.endpoints.bss }}
  {{ printf "HUAWEICLOUD_SDK_REGION_BSS_%s" $regionKey }}: {{ .Values.sdk.endpoints.bss | quote }}
  {{- end }}
{{- end }}
