apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-provider-huawei.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
    {{- include "karpenter-provider-huawei.selectorLabels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "karpenter-provider-huawei.selectorLabels" . | nindent 4 }}
