apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-provider-huawei.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
    {{- include "karpenter-provider-huawei.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: {{ .Values.controller.metrics.port }}
    protocol: TCP
    targetPort: http-metrics
  selector:
    {{- include "karpenter-provider-huawei.selectorLabels" . | nindent 4 }}
