{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "karpenter-provider-huawei.labels" . | nindent 4 }}
  name: {{ include "karpenter-provider-huawei.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
