# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: karpenter-provider-huawei
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
spec:
  namespaceSelector:
    matchNames:
      - system
  endpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: karpenter-provider-huawei
