# This rule is not used by the project karpenter-provider-huawei itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the karpenter.k8s.huawei.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: karpenter-provider-huawei
    app.kubernetes.io/managed-by: kustomize
  name: ccenodeclass-editor-role
rules:
- apiGroups:
  - karpenter.k8s.huawei
  resources:
  - ccenodeclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.k8s.huawei
  resources:
  - ccenodeclasses/status
  verbs:
  - get
