---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - karpenter.k8s.huawei
  resources:
  - ecsnodeclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.k8s.huawei
  resources:
  - ecsnodeclasses/finalizers
  verbs:
  - update
- apiGroups:
  - karpenter.k8s.huawei
  resources:
  - ecsnodeclasses/status
  verbs:
  - get
  - patch
  - update
