apiVersion: karpenter.k8s.huawei/v1alpha1
kind: ECSNodeClass
metadata:
  labels:
    app.kubernetes.io/name: karpenter-provider-huawei
    app.kubernetes.io/managed-by: kustomize
  name: ecsnodeclass-sample
spec:
  vpcId: 123e4567-e89b-12d3-a456-426614174000
  hmiSelectorTerms:
    - alias: Huawei Cloud EulerOS 2.0
  rootVolume:
    size: 40
    volumeType: SSD
  subnetSelectorTerms:
    - id: 323e4567-e89b-12d3-a456-426614174000
