apiVersion: karpenter.k8s.huawei/v1alpha1
kind: CCENodeClass
metadata:
  labels:
    app.kubernetes.io/name: karpenter-provider-huawei
    app.kubernetes.io/managed-by: kustomize
  name: ccenodeclass-sample
spec:
  subnetSelectorTerms:
    - id: 323e4567-e89b-12d3-a456-426614174000
  imsSelector:
    imsFamily: HCE OS 2.0
  blockDeviceMappings:
    k8s:
      volumeSize: 120
      volumeType: SAS
    root:
      volumeSize: 120
      volumeType: SATA
    users:
      - volumeSize: 100
        volumeType: SAS
      - volumeSize: 100
        volumeType: SATA
  runtimeConfiguration:
    type: containerd
  login:
    userPassword:
      username: root
      password: "<salted-and-encrypted-password>"
